name = "fsparse"
version = "0.1.1"
license = "MIT"
author = "José Alves"
maintainer = "jose.alves@transvalor.com"
copyright = "Copyright 2023, Jose Alves"

[dev-dependencies.test-drive]
git = "https://github.com/fortran-lang/test-drive"
tag = "v0.4.0"

[preprocess.cpp]
suffixes = [".f90", ".fypp"]
