name = "fsparse"
version = "0.1.0"
license = "MIT"
author = "José Alves"
maintainer = "jose.alves@transvalor.com"
copyright = "Copyright 2023, Jose Alves"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

